apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crw-browser-profile
  namespace: bryzek-production
  labels:
    app: court-reserve-workers
    app.kubernetes.io/name: court-reserve-workers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 10Gi
