apiVersion: v1
kind: Service
metadata:
  name: court-reserve-workers
  namespace: bryzek-production
  labels:
    app: court-reserve-workers
    app.kubernetes.io/name: court-reserve-workers
spec:
  type: ClusterIP
  selector:
    app: court-reserve-workers
  ports:
    - name: http
      port: 8787
      targetPort: 8787
      protocol: TCP
