require 'set'
require 'find'
require 'json'

module Codegen
  module Sync
    MARKER = "generated by api builder".freeze
    MARKER_SCAN_LINES = 12

    # Leading tokens (after lstrip) that mark a line as a comment across the
    # generated languages: Scala/TS block+line comments, routes/# , Elm --/{-.
    COMMENT_PREFIXES = ["*", "//", "/*", "#", "--", "{-", "-}"].freeze

    module_function

    def classify_diff(porcelain)
      porcelain.to_s.strip.empty? ? :in_sync : :changed
    end

    # True when a single file's unified diff changes ONLY comment (or blank)
    # lines. The apibuilder generator stamps a fresh `Service version:`
    # timestamp into every generated file's header comment, so a no-op regen
    # rewrites all of them; reverting comment-only changes keeps that churn out
    # of the diff/PR. Returns false for an empty diff (nothing to revert).
    def comment_only_diff?(diff_text)
      # Parse hunk-aware: only +/- lines AFTER an `@@` header are content.
      # (A removed Elm `--` comment renders as `--- …`, which would otherwise
      # collide with the `---`/`+++` file-header lines that precede any hunk.)
      in_hunk = false
      changed = []
      diff_text.to_s.each_line do |l|
        if l.start_with?("@@")
          in_hunk = true
        elsif in_hunk && (l.start_with?("+") || l.start_with?("-"))
          changed << l
        end
      end
      return false if changed.empty?
      changed.all? do |l|
        content = l[1..].to_s.lstrip
        content.empty? || COMMENT_PREFIXES.any? { |p| content.start_with?(p) }
      end
    end

    # URL of the first OPEN PR whose head branch is a codegen-sync branch, given
    # the JSON from `gh pr list --json url,headRefName`, or nil. The gate against
    # duplicate sweeps is an open PR, not a leftover branch.
    def open_codegen_pr_url(gh_json, branch_prefix)
      data = begin
        JSON.parse(gh_json.to_s)
      rescue JSON::ParserError
        nil
      end
      return nil unless data.is_a?(Array)
      pr = data.find { |p| p.is_a?(Hash) && p["headRefName"].to_s.start_with?(branch_prefix) }
      pr && pr["url"]
    end

    # Files to delete before rerunning `api`: everything carrying the
    # "Generated by API Builder" header marker. Every generated file (routes,
    # Scala, TS, Elm) carries it — and so do orphans, since they were generated
    # — so this catches everything a config-target-dir sweep would, WITHOUT
    # deleting hand-written files that share a generator output dir (e.g.
    # platform's api/conf holds generated *.routes alongside hand-written
    # application.conf / logback.xml). Skips .git.
    def generated_paths(repo_dir)
      root = File.expand_path(repo_dir)
      paths = Set.new
      Find.find(root) do |p|
        if File.basename(p) == ".git" && File.directory?(p)
          Find.prune
        elsif File.file?(p) && marker?(p)
          paths << p
        end
      end
      paths.to_a
    end

    def marker?(path)
      File.foreach(path).first(MARKER_SCAN_LINES).any? { |l| l.downcase.include?(MARKER) }
    rescue ArgumentError # binary file
      false
    end

    def verify_cmd_for(stack, full_tests:)
      case stack
      when :scala     then full_tests ? "sbt test" : "sbt Test/compile"
      when :sveltekit then "npm run check"
      when :elm       then "./review.sh"
      else raise "no verify command for stack #{stack.inspect}"
      end
    end

    def fix_prompt(repo:, branch:, verify_cmd:, regen_only:, build_error: nil)
      lines = []
      lines << "You are in a fresh clone of #{repo} on branch #{branch}."
      lines << "Generated apibuilder/DAO code was regenerated by running `api` (wipe generated files, then `api`)."
      lines << "The regenerated client changed the codegen surface. Your job:"
      lines << "1. Make the repo build: run `#{verify_cmd}` and fix any consuming code so it matches the new generated client."
      lines << "   Important: never edit generated files (files under the .api/config.pkl target dirs or carrying the 'Generated by API Builder' header). Fix the callers instead."
      if build_error && !build_error.strip.empty?
        lines << "The current build error is:"
        lines << build_error.strip
      end
      lines << "2. Commit the working, green tree and push branch #{branch}."
      lines << "3. Open a draft PR with `gh pr create --draft`."
      unless regen_only
        lines << "4. Then complete the full workflow: mark the PR ready (`gh pr ready`), run the code-reviewer agent, then the code-review:code-review skill, iterating on both."
        lines << "5. Rebase onto latest origin/main, rerun `api` codegen, and resolve any compile/lint/test failures. Force-push the rebased branch after fetching."
      end
      lines << "Do NOT merge to main under any circumstance — leave the PR review-ready for Mike."
      lines.join("\n")
    end
  end
end
