require 'set'

module Codegen
  module Sync
    MARKER = "generated by api builder".freeze
    MARKER_SCAN_LINES = 12

    module_function

    def classify_diff(porcelain)
      porcelain.to_s.strip.empty? ? :in_sync : :changed
    end

    def generated_paths(repo_dir, api_config)
      paths = Set.new
      api_config.target_dirs.each do |rel|
        base = File.expand_path(rel.sub(%r{\A\./}, ""), repo_dir)
        next unless File.directory?(base)
        Dir.glob(File.join(base, "**", "*"), File::FNM_DOTMATCH)
           .select { |p| File.file?(p) }
           .each { |p| paths << p }
      end
      Dir.glob(File.join(repo_dir, "**", "*"), File::FNM_DOTMATCH).each do |p|
        next if p.include?("#{File::SEPARATOR}.git#{File::SEPARATOR}")
        next unless File.file?(p)
        paths << p if marker?(p)
      end
      paths.to_a
    end

    def marker?(path)
      File.foreach(path).first(MARKER_SCAN_LINES).any? { |l| l.downcase.include?(MARKER) }
    rescue ArgumentError # binary file
      false
    end
  end
end
