require 'set'
require 'find'
require 'json'

module Codegen
  module Sync
    MARKER = "generated by api builder".freeze
    MARKER_SCAN_LINES = 12

    # Leading tokens (after lstrip) that mark a line as a comment across the
    # generated languages: Scala/TS block+line comments, routes/# , Elm --/{-.
    COMMENT_PREFIXES = ["*", "//", "/*", "#", "--", "{-", "-}"].freeze

    module_function

    def classify_diff(porcelain)
      porcelain.to_s.strip.empty? ? :in_sync : :changed
    end

    # True when a file's unified diff has NO real content change — only comment
    # and/or whitespace/newline noise. Two sources of noise on a no-op regen:
    #   1. the apibuilder `Service version:` timestamp in the header comment;
    #   2. the generator omits the trailing newline that committed files have,
    #      so the last line shows as `-X` / `+X` for an identical X (with a
    #      `\ No newline at end of file` marker).
    # Compares the non-comment, non-blank removed vs added lines after stripping
    # trailing whitespace; equal multisets ⇒ nothing real changed, so revert.
    # Returns false for an empty diff.
    def noise_only_diff?(diff_text)
      # Hunk-aware: only +/- lines AFTER an `@@` header are content (a removed
      # Elm `--` comment renders as `--- …`, which must not be confused with the
      # `---`/`+++` file-header lines that precede any hunk).
      removed = []
      added = []
      in_hunk = false
      diff_text.to_s.each_line do |l|
        if l.start_with?("@@")
          in_hunk = true
        elsif in_hunk && l.start_with?("+") && !l.start_with?("+++")
          added << l[1..].to_s
        elsif in_hunk && l.start_with?("-") && !l.start_with?("---")
          removed << l[1..].to_s
        end
      end
      return false if removed.empty? && added.empty?
      meaningful = lambda do |lines|
        lines.map(&:rstrip)
             .reject { |c| c.empty? || COMMENT_PREFIXES.any? { |p| c.lstrip.start_with?(p) } }
             .sort
      end
      meaningful.call(removed) == meaningful.call(added)
    end

    # URL of the first OPEN PR whose head branch is a codegen-sync branch, given
    # the JSON from `gh pr list --json url,headRefName`, or nil. The gate against
    # duplicate sweeps is an open PR, not a leftover branch.
    def open_codegen_pr_url(gh_json, branch_prefix)
      data = begin
        JSON.parse(gh_json.to_s)
      rescue JSON::ParserError
        nil
      end
      return nil unless data.is_a?(Array)
      pr = data.find { |p| p.is_a?(Hash) && p["headRefName"].to_s.start_with?(branch_prefix) }
      pr && pr["url"]
    end

    # Files to delete before rerunning `api`: everything carrying the
    # "Generated by API Builder" header marker. Every generated file (routes,
    # Scala, TS, Elm) carries it — and so do orphans, since they were generated
    # — so this catches everything a config-target-dir sweep would, WITHOUT
    # deleting hand-written files that share a generator output dir (e.g.
    # platform's api/conf holds generated *.routes alongside hand-written
    # application.conf / logback.xml). Skips .git.
    def generated_paths(repo_dir)
      root = File.expand_path(repo_dir)
      paths = Set.new
      Find.find(root) do |p|
        if File.basename(p) == ".git" && File.directory?(p)
          Find.prune
        elsif File.file?(p) && marker?(p)
          paths << p
        end
      end
      paths.to_a
    end

    # The marker only counts on a COMMENT line — generated headers are always
    # comments, while source code can carry the marker in a string literal
    # (platform's GeneratedHeader.scala EMITS the header and was wiped as if it
    # were generated output, breaking the build).
    def marker?(path)
      File.foreach(path).first(MARKER_SCAN_LINES).any? { |l| marker_comment_line?(l) }
    rescue ArgumentError # binary file
      false
    end

    def marker_comment_line?(line)
      stripped = line.lstrip
      stripped.downcase.include?(MARKER) && COMMENT_PREFIXES.any? { |p| stripped.start_with?(p) }
    end

    def verify_cmd_for(stack, full_tests:)
      case stack
      when :scala     then full_tests ? "sbt test" : "sbt Test/compile"
      when :sveltekit then "npm run check"
      when :elm       then "./review.sh"
      else raise "no verify command for stack #{stack.inspect}"
      end
    end

    # Minimal, bounded prompt for the headless per-repo session: get the repo to
    # a pushed PR and STOP. It deliberately does NOT run code-review rounds or a
    # rebase — review happens in Reviewable once the PR is open, and dragging a
    # full review workflow into every session is what made sweeps take ~20 min
    # per repo (the Claude timeout) and look hung.
    def fix_prompt(repo:, branch:, verify_cmd:, regen_only:, build_error: nil)
      lines = []
      lines << "You are in a fresh clone of #{repo} on branch #{branch}. Its generated"
      lines << "apibuilder/DAO code was just regenerated by running `api`."
      if regen_only
        lines << "Commit the regenerated files as-is, push branch #{branch}, and open a DRAFT"
        lines << "PR with `gh pr create --draft --fill --head #{branch}`. Do not build, fix, or review."
      else
        lines << "Do exactly this and stop once the PR is open:"
        lines << "1. Make it build: run `#{verify_cmd}` and fix ONLY the consuming code needed"
        lines << "   to match the regenerated client. NEVER edit generated files (they carry a"
        lines << "   'Generated by API Builder' header) — fix the callers instead."
        if build_error && !build_error.strip.empty?
          lines << "   The current build error is:"
          lines << "   #{build_error.strip}"
        end
        lines << "2. Commit the working, green tree and push branch #{branch}."
        lines << "3. Open the PR: `gh pr create --fill --head #{branch}` (the clone is"
        lines << "   single-branch, so without --head gh cannot see the pushed branch),"
        lines << "   then `gh pr ready` if it opened as a draft."
      end
      lines << "Do NOT run code reviews, do NOT rebase, and do NOT merge to main. Review"
      lines << "happens in Reviewable once the PR exists — stop as soon as it does."
      lines.join("\n")
    end
  end
end
