apiVersion: v1
kind: Service
metadata:
  name: workers
  namespace: bryzek-production
  labels:
    app: workers
    app.kubernetes.io/name: workers
spec:
  type: ClusterIP
  selector:
    app: workers
  ports:
    - name: http
      port: 8787
      targetPort: 8787
      protocol: TCP
