# This class generated by Chat GPT from example json structure

require 'json'

class App
  attr_accessor :name, :scala, :port, :elm, :hugo, :sveltekit

  def initialize(json_data)
    @name = json_data['name']
    @scala = json_data['scala'] ? ScalaConfig.new(json_data['scala']) : nil
    @port = json_data['port']
    @elm = json_data['elm'] ? ElmConfig.new(json_data['elm']) : nil
    @hugo = json_data['hugo'] ? HugoConfig.new(json_data['hugo']) : nil
    @sveltekit = json_data['sveltekit'] ? SveltekitConfig.new(json_data['sveltekit']) : nil
  end
end

class HugoConfig
  def initialize(json_data)
  end
end

class SveltekitConfig
  def initialize(json_data)
  end
end

class ElmConfig
  attr_accessor :rewrites

  def initialize(json_data)
    @rewrites = (json_data['rewrites'] || []).map { |d| ElmRewrite.new(d) }
  end
end

class ElmRewrite
  attr_accessor :from, :to

  def initialize(json_data)
    @from = json_data['from']
    @to = json_data['to']
  end
end

class ScalaConfig
  attr_accessor :production, :development

  def initialize(json_data)
    @production = ScalaEnvironment.new(json_data['production'])
    @development = ScalaEnvironment.new(json_data['development'])
  end
end

class ScalaEnvironment
  attr_accessor :database

  def initialize(json_data)
    @database = Database.new(json_data['database'])
  end
end

class Database
  attr_accessor :name, :host, :user, :port

  def initialize(json_data)
    @name = json_data['name']
    @host = json_data['host']
    @user = json_data['user']
    @port = json_data['port']
  end
end
