# This class generated by Chat GPT from example json structure

require 'json'

class App
  attr_accessor :name, :repo, :scala, :port, :elm, :sveltekit, :docker_k8s, :digital_ocean_account

  def initialize(json_data)
    @name = json_data['name']
    @repo = json_data['repo']
    # Default matches the pkl schema; the fallback covers dist json generated
    # before the field existed.
    @digital_ocean_account = json_data['digital_ocean_account'] || 'personal'
    @scala = json_data['scala'] ? ScalaConfig.new(json_data['scala']) : nil
    @port = json_data['port']
    @elm = json_data['elm'] ? ElmConfig.new(json_data['elm']) : nil
    @sveltekit = json_data['sveltekit'] ? SveltekitConfig.new(json_data['sveltekit']) : nil
    @docker_k8s = json_data['docker_k8s'] ? DockerK8sConfig.new(json_data['docker_k8s']) : nil
  end

  # The GitHub repository name, which is also the checkout directory under ~/code.
  # Defaults to the app name — the case for every app today — but a deployable can be
  # renamed ahead of its repo, so anything filesystem- or git-facing keys off this
  # rather than off `name`.
  def repo_name
    @repo.nil? || @repo.empty? ? @name : @repo.split("/").last
  end

  # True when this deployable is built from the ~/code/<repo_base> checkout.
  # More than one deployable can share a repo — platform and playbook-api are
  # the same codebase deployed to different DO accounts — and release-db uses
  # this to find every database a schema repo must be applied to.
  def built_from?(repo_base)
    repo_name == repo_base
  end
end

class DockerK8sConfig
  attr_accessor :build_script, :manifests_dir, :rollout_target, :namespace

  def initialize(json_data)
    @build_script = json_data['build_script']
    @manifests_dir = json_data['manifests_dir']
    @rollout_target = json_data['rollout_target']
    @namespace = json_data['namespace']
  end
end

class SveltekitConfig
  attr_reader :deploy_targets

  def initialize(json_data)
    # The pkl schema requires a non-empty deploy_targets with an explicit
    # cloudflare_account per target — there is no implicit default account.
    @deploy_targets = (json_data['deploy_targets'] || []).map { |d| CloudflareDeploy.new(d) }
  end
end

class CloudflareDeploy
  attr_reader :cloudflare_account, :wrangler_env, :pages_project

  def initialize(json_data)
    @cloudflare_account = json_data['cloudflare_account']
    @wrangler_env = json_data['wrangler_env']
    @pages_project = json_data['pages_project']
  end

  # The Cloudflare Pages project this target deploys to. Defaults to the app name: every
  # Pages app names its project after itself, and only a mirror target that deviates (e.g.
  # playbook-www -> "plybk-www") sets pages_project explicitly. Always resolving a name keeps
  # `wrangler pages deploy` non-interactive — see release-sveltekit.
  def pages_project_for(app_name)
    @pages_project || app_name
  end
end

class ElmConfig
  attr_accessor :rewrites

  def initialize(json_data)
    @rewrites = (json_data['rewrites'] || []).map { |d| ElmRewrite.new(d) }
  end
end

class ElmRewrite
  attr_accessor :from, :to

  def initialize(json_data)
    @from = json_data['from']
    @to = json_data['to']
  end
end

class ScalaConfig
  attr_accessor :production, :development

  def initialize(json_data)
    @production = ScalaEnvironment.new(json_data['production'])
    @development = ScalaEnvironment.new(json_data['development'])
  end
end

class ScalaEnvironment
  attr_accessor :database

  def initialize(json_data)
    @database = Database.new(json_data['database'])
  end
end

class Database
  attr_accessor :name, :host, :user, :port

  def initialize(json_data)
    @name = json_data['name']
    @host = json_data['host']
    @user = json_data['user']
    @port = json_data['port']
  end
end
